### PR TITLE
check for CATKIN_ENABLE_TESTING

### PR DESCRIPTION
**Pull request by bulwahn**

### CODE REVIEW

**Comment by dgossow** [comment]
@wjwwood Could you someone at OSRF release this?

**Comment by wjwwood** [comment]
I can, but we should really find someone to help you maintain if you don't have time to do it.

**Comment by dgossow** [comment]
Yeah, I don't even really know what this package does. The only reason I'm maintainer is that I was tasked to convert this to catkin back at Willow.

**Comment by dgossow** [comment]
Maybe @vpradeep07 wants to have it back?

**Comment by wjwwood** [comment]
I suppose it assembles lasers, which sounds pretty awesome, though might not be exactly what it sounds like.

Either way we should mark it as unmaintained in Indigo and at best solicit for new maintainers on the mailing list.

**Comment by vpradeep07** [comment]
Wow... didn't realize this piece of code was still around :-)

It maintains a cache of the most recent used laser messages, and then generates an aggregated point cloud for each client request.  Basically, it's a bunch of glue code between TF, laser messages, point clouds, and ROS services.

Marking it as unmaintained sounds fine by me.

**Pull request merged**
