### PR TITLE
[ROS-O] update header include

### PR DESCRIPTION
**Pull request by v4hn**
to get rid of deprecation warnings

### CODE REVIEW

**Review by jonbinney — APPROVED** [review]
Looks good, and does get rid of the warnings.

**Comment by jonbinney** [comment]
Thanks @v4hn !

**Comment by jonbinney** [comment]
@v4hn now that this is merged, are you going to keep using the fork from ros-o? I'll try to be better about quickly merging these PRs.

**Comment by v4hn** [comment]
No. When all required changes are upstream, the ros-o fork is disabled again.

Thank you for responding without politics. :+1:

**Pull request merged**
